Reordering functions, minor cleanup

diff --git a/spawn b/spawn
--- a/spawn
+++ b/spawn
@@ -457,44 +457,10 @@ cleanup() {
     fi
 }
 
-spawn_root_nspawn() {
-    local IFS="$S"
-    local A= cmd=
-
-    # systemd-nspawn runs 'getent passwd <user>' inside the container to get
-    # passwd entry for the user or fails with "Failed to resolve user <user>"
-    if [ "$container_user" ]; then
-        A="$A$S--user=$container_user"
-    fi
-
-    if ! passwd_exists || ! user_exists "$container_user"; then
-        die "the specified user '$container_user' is not found inside the chroot"
-    fi
-
-    if [ "$share_system" ]; then
-        A="$A$S--share-system"
-    fi
-
-    setup_env A
-
-    if [ "${spawn_boot-}" ]; then
-        A="$A$S--boot"
-    fi
-
-    if [ "${container_command-}" ]; then
-        cmd="$container_command"
-    else
-        cmd="/bin/sh${S}-c${S}cd && exec /bin/bash -l"
-    fi
-
-    su_run systemd-nspawn $A $additional_args -D "$root_dir" $cmd
-}
-
 spawn_root_chroot() {
     local IFS="$S"
     local path= setarch= env= ssh_sock_dir=
     local cmd= mount_cmd= chroot_cmd= i=
-    local pa_sock= in_pa_sock=
 
     if ! passwd_exists || ! user_exists "$container_user"; then
         die "the specified user '$container_user' is not found inside the chroot"
@@ -554,6 +520,39 @@ EOF
     su_run $setarch env - $env unshare -m /bin/sh -c "$mount_cmd"
 }
 
+spawn_root_nspawn() {
+    local IFS="$S"
+    local A= cmd=
+
+    # systemd-nspawn runs 'getent passwd <user>' inside the container to get
+    # passwd entry for the user or fails with "Failed to resolve user <user>"
+    if [ "$container_user" ]; then
+        A="$A$S--user=$container_user"
+    fi
+
+    if ! passwd_exists || ! user_exists "$container_user"; then
+        die "the specified user '$container_user' is not found inside the chroot"
+    fi
+
+    if [ "$share_system" ]; then
+        A="$A$S--share-system"
+    fi
+
+    setup_env A
+
+    if [ "${spawn_boot-}" ]; then
+        A="$A$S--boot"
+    fi
+
+    if [ "${container_command-}" ]; then
+        cmd="$container_command"
+    else
+        cmd="/bin/sh${S}-c${S}cd && exec /bin/bash -l"
+    fi
+
+    su_run systemd-nspawn $A $additional_args -D "$root_dir" $cmd
+}
+
 spawn_root_docker() {
     local IFS="$(printf '\n\t')"
     local A=
@@ -588,6 +587,12 @@ trap cleanup EXIT
 container_home=$(find_user_info home)
 [ "$container_home" ] ||
     die "failed to find user's home directory"
+
+# ensure these directories exist and owned by user
+if [ "$root_dir" ]; then
+    in_mkdir "$root_dir/$(get_runtime_dir)"
+    in_mkdir "$root_dir/$(get_config_dir)"
+fi
 
 if [ "$with_x11" ]; then
     extract_xauth
