Refactoring permission handling
Work in progress to allow host and container users to have different
UIDs.

diff --git a/spawn b/spawn
--- a/spawn
+++ b/spawn
@@ -10,6 +10,7 @@ root_dir=
 container_type=
 container_name=
 container_user="dev"
+container_group="users"
 container_home="/home/$container_user"
 container_command=
 additional_args=
@@ -234,14 +235,21 @@ find_home_dir() {
 }
 
 find_user_info() {
-    local name="$1" field="${2:-home}"
+    local field="${1:-home}"
     [ -f "$root_dir/etc/passwd" ] || return
     while IFS=: read -r user pass uid gid gecos home shell; do
-        if [ "$user" = "$name" ]; then
+        if [ "$user" = "$container_user" ]; then
             eval "echo \$$field"
             break
         fi
     done < "$root_dir/etc/passwd"
+}
+
+get_userspec() {
+    local uid= gid=
+    uid=$(find_user_info uid)
+    gid=$(find_user_info gid)
+    echo "$uid:$gid"
 }
 
 set_container_home() {
@@ -252,23 +260,33 @@ set_container_home() {
     fi
 }
 
-get_runtime_dir() {
-    echo "/run/user/$1"
+in_mkdir() {
+    local uid="$(find_user_info uid)" gid="$(find_user_info gid)"
+    su_run install -o $uid -g $gid -d "$1" || die
 }
 
-prepare_runtime_dir() {
-    local uid= gid= dir=
+in_touch() {
+    local uid="$(find_user_info uid)" gid="$(find_user_info gid)"
+    su_run install -o "$uid" -g "$gid" -d "$(dirname "$1")" || die
+    su_run touch "$1" || die
+    su_run chown "$uid:$gid" "$1" || die
+}
 
-    uid=$(find_user_info "$container_user" uid)
-    gid=$(find_user_info "$container_user" gid)
-    dir=$(get_runtime_dir "$uid")
+in_mount() {
+    su_run mount "$@" || die
+}
 
-    # this creates empty pulse dir even if it's not needed but makes permission
-    # handling simpler
-    su_run mkdir -p "$root_dir/$dir/pulse" || die
-    su_run chown -R "$uid:$gid" "$root_dir/$dir" || die
+get_config_dir() {
+    local config_dir="/home/$container_user/.config"
 
-    echo "$dir"
+    echo "$config_dir${1:+/$1}"
+}
+
+get_runtime_dir() {
+    local uid="$(find_user_info uid)"
+    local runtime_dir="/run/user/$uid"
+
+    echo "$runtime_dir${1:+/$1}"
 }
 
 get_pa_socket() {
@@ -279,9 +297,21 @@ get_pa_socket() {
     fi
 }
 
+get_in_pa_socket() {
+    echo "$(get_runtime_dir pulse)/native"
+}
+
 validate_pa_socket() {
     [ -S "$1" ] || die "PulseAudio socket '$1' does not exist"
-    echo "$1"
+}
+
+copy_pa_cookie() {
+    local cookie_file="$HOME/.config/pulse/cookie"
+    local dest_dir="$root_dir/$(get_config_dir pulse)"
+    [ -f "$cookie_file" ] || die "PulseAudio cookie file '$cookie_file' was not found"
+    in_mkdir "$dest_dir"
+    su_run cp -f "$cookie_file" "$dest_dir/cookie" || die
+    su_run chown "$(get_userspec)" "$dest_dir/cookie" || die
 }
 
 extract_xauth() {
@@ -290,12 +320,6 @@ extract_xauth() {
     # differ from the host and default Xauthority files are hostname specific.
     # See http://stackoverflow.com/a/25280523 for details.
     xauth nlist "$DISPLAY" | sed 's/^..../ffff/' | xauth -f "$xauth_file" nmerge -
-}
-
-copy_pulseaudio_cookie() {
-    mkdir -p "$root_dir/$container_home/.config/pulse"
-    cp -f "$HOME/.config/pulse/cookie" \
-        "$root_dir/$container_home/.config/pulse/cookie"
 }
 
 copy_resolv_conf() {
@@ -324,7 +348,7 @@ cleanup() {
 
 spawn_root_nspawn() {
     local IFS="$S"
-    local A= pa_socket= cmd=
+    local A= pa_sock= in_pa_sock= cmd=
 
     # systemd-nspawn runs 'getent passwd <user>' inside the container to get
     # passwd entry for the user or fails with "Failed to resolve user <user>"
@@ -363,10 +387,12 @@ spawn_root_nspawn() {
     fi
 
     if [ "$with_pulseaudio" ]; then
-        pa_socket=$(validate_pa_socket "$(get_pa_socket)")
-        A="$A$S--setenv=PULSE_SERVER=$pa_socket"
-        A="$A$S--bind=$pa_socket"
-        # copy_pulseaudio_cookie
+        pa_sock=$(get_pa_socket)
+        validate_pa_socket "$pa_sock"
+        in_pa_sock="$(get_in_pa_socket)"
+        A="$A$S--setenv=PULSE_SERVER=$in_pa_sock"
+        A="$A$S--bind=$pa_sock:$in_pa_sock"
+        copy_pa_cookie
     fi
 
     if [ "${spawn_boot-}" ]; then
@@ -385,7 +411,8 @@ spawn_root_nspawn() {
 spawn_root_chroot() {
     local IFS="$S"
     local userspec= path= setarch= env= ssh_sock_dir=
-    local cmd= mount_cmd= chroot_cmd= i= pa_sock= pa_sock_dir=
+    local cmd= mount_cmd= chroot_cmd= i=
+    local pa_sock= in_pa_sock=
 
     if [ "$container_user" = 'root' ]; then
         userspec="0:0"
@@ -461,10 +488,13 @@ EOF
     fi
 
     if [ "$with_pulseaudio" ]; then
-        pa_sock=$(validate_pa_socket "$(get_pa_socket)")
-        pa_sock_dir=$(prepare_runtime_dir)/pulse
-        env="${env}${S}PULSE_SERVER=$pa_sock_dir/native"
-        su_run mount --bind "$(dirname "$pa_sock")" "$root_dir/$pa_sock_dir" || die
+        pa_sock=$(get_pa_socket)
+        validate_pa_socket "$pa_sock"
+        in_pa_sock="$(get_in_pa_socket)"
+        env="${env}${S}PULSE_SERVER=$in_pa_sock"
+        in_touch "$root_dir/$in_pa_sock"
+        su_run mount --bind "$pa_sock" "$root_dir/$in_pa_sock" || die
+        copy_pa_cookie
     fi
 
     if [ "${container_command-}" ]; then
